export * from './src/decorators/generic'
export * from './src/decorators/endpoints'
export * from './src/service/service'
export * from './src/service/serviceBuilder'
export * from './src/kaqiPlaceholder'
