"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CUSTOM = exports.CONNECT = exports.TRACE = exports.OPTIONS = exports.HEAD = exports.DELETE = exports.PATCH = exports.PUT = exports.POST = exports.GET = void 0;
const sharedUtils_1 = require("./sharedUtils");
const buildEndpointDecorator = (method) => (url) => (0, sharedUtils_1.buildMethodDecorator)({ url, method });
exports.GET = buildEndpointDecorator('GET');
exports.POST = buildEndpointDecorator('POST');
exports.PUT = buildEndpointDecorator('PUT');
exports.PATCH = buildEndpointDecorator('PATCH');
exports.DELETE = buildEndpointDecorator('DELETE');
exports.HEAD = buildEndpointDecorator('HEAD');
exports.OPTIONS = buildEndpointDecorator('OPTIONS');
exports.TRACE = buildEndpointDecorator('TRACE');
exports.CONNECT = buildEndpointDecorator('CONNECT');
const CUSTOM = (method, url) => (0, sharedUtils_1.buildMethodDecorator)({ url, method });
exports.CUSTOM = CUSTOM;
