name: build-test
on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
