name: CI
on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - uses: actions/upload-artifact@master
        with:
          name: build
          path: lib

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: build
          path: lib

      - run: cd lib

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
