name: Publish
on:
  push:
    branches:
      - release

permissions:
  contents: write
  deployments: write
  pull-requests: write
  issues: write

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
